# Site settings
title: My Dymaxion Blog 
email: hello@brianburnley.com
description: Brian's Plucky, Bucky Blog
baseurl: ""
url: ""
twitter_username: roccaturi
github_username:  roccaturi

# Build settings
markdown: kramdown
